version: '3.8'

services:
    cron:
        build:
            context: ./docker/server

        volumes:
            - ./docker/server/crontabs/root:/etc/crontabs/root

        networks:
            - network2

    webserver:
        image: nginx:alpine

        volumes:
            - ./www:/var/www/html
            - ./docker/server/nginx.conf:/etc/nginx/conf.d/default.conf

        depends_on:
            - php
        ports:
            - ${WEBSERVER_PORT}:80

        networks:
            - network2

    php:
        build:
            context: ./docker/php

        volumes:
            - ./www:/var/www/html
            - ./docker/php/php.ini:/usr/local/etc/php/conf.d/docker-fpm.ini
            - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini

        extra_hosts:
            -   "host.docker.internal:host-gateway"

        networks:
            - network2


    db:
        image: mysql:latest
        volumes:
            - ./docker/db:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        environment:
            PMA_HOST: ${PMA_HOST}
            PMA_USER: ${PMA_USER}
            PMA_PASSWORD: ${PMA_PASSWORD}
        ports:
            - "8080:80"
        depends_on:
            - db

        networks:
            - network2

networks:
    network2:
        name: "network2"