version: '3.8'

services:
    webserver:
        image: nginx:alpine
        volumes:
            - ./public:/var/www/html
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
        ports:
            - ${WEBSERVER_PORT}:80

    php:
        image: php:8.3-fpm
        working_dir: /application
        volumes:
            - ./public:/var/www/html
#            - ./docker/php/php.ini:/usr/local/etc/php/php.ini

    db:
        image: mysql:latest
        volumes:
            - ./docker/db:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: local
            MYSQL_USER: local
            MYSQL_PASSWORD: local

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        environment:
            PMA_HOST: db
            PMA_USER: local
            PMA_PASSWORD: local
        ports:
            - "8080:80"
        depends_on:
            - db